2025-09-30 23:30:05 INFO root: Logging to /home/nodadyoushutup/code/transcoder/core/backend/logs/backend-20250930-233005.log
2025-09-30 23:30:07 INFO app: Ensured admin account 'admin' (id=1)
2025-09-30 23:30:07 INFO werkzeug: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.1.150:5001
2025-09-30 23:30:07 INFO werkzeug: [33mPress CTRL+C to quit[0m
2025-09-30 23:30:07 ERROR app.services.transcoder_client: Transcoder service request failed: HTTPConnectionPool(host='localhost', port=5003): Max retries exceeded with url: /transcode/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65e6d5df60>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-09-30 23:30:07 INFO werkzeug: 192.168.1.23 - - [30/Sep/2025 23:30:07] "[35m[1mGET /transcode/status HTTP/1.1[0m" 503 -
2025-09-30 23:30:10 INFO werkzeug: 127.0.0.1 - - [30/Sep/2025 23:30:10] "GET /media/init-1.m4s HTTP/1.1" 200 -
2025-09-30 23:30:10 INFO werkzeug: 127.0.0.1 - - [30/Sep/2025 23:30:10] "GET /media/init-0.m4s HTTP/1.1" 200 -
2025-09-30 23:30:11 ERROR app.services.transcoder_client: Transcoder service request failed: HTTPConnectionPool(host='localhost', port=5003): Max retries exceeded with url: /transcode/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65e6d5f1c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-09-30 23:30:11 INFO werkzeug: 192.168.1.23 - - [30/Sep/2025 23:30:11] "[35m[1mGET /transcode/status HTTP/1.1[0m" 503 -
2025-09-30 23:30:22 INFO werkzeug: 192.168.1.23 - - [30/Sep/2025 23:30:22] "GET /auth/session HTTP/1.1" 200 -
2025-09-30 23:30:22 INFO werkzeug: 192.168.1.23 - - [30/Sep/2025 23:30:22] "GET /auth/session HTTP/1.1" 200 -
2025-09-30 23:30:22 ERROR app.services.transcoder_client: Transcoder service request failed: HTTPConnectionPool(host='localhost', port=5003): Max retries exceeded with url: /transcode/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65e6d5e7d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-09-30 23:30:22 INFO werkzeug: 192.168.1.23 - - [30/Sep/2025 23:30:22] "[35m[1mGET /transcode/status HTTP/1.1[0m" 503 -
2025-09-30 23:30:22 ERROR app.services.transcoder_client: Transcoder service request failed: HTTPConnectionPool(host='localhost', port=5003): Max retries exceeded with url: /transcode/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65e6e04730>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-09-30 23:30:22 INFO werkzeug: 192.168.1.23 - - [30/Sep/2025 23:30:22] "[35m[1mGET /transcode/status HTTP/1.1[0m" 503 -
2025-09-30 23:30:27 ERROR app.services.transcoder_client: Transcoder service request failed: HTTPConnectionPool(host='localhost', port=5003): Max retries exceeded with url: /transcode/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65e6e06140>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-09-30 23:30:27 INFO werkzeug: 192.168.1.23 - - [30/Sep/2025 23:30:27] "[35m[1mGET /transcode/status HTTP/1.1[0m" 503 -
2025-09-30 23:30:32 ERROR app.services.transcoder_client: Transcoder service request failed: HTTPConnectionPool(host='localhost', port=5003): Max retries exceeded with url: /transcode/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65e6e05330>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-09-30 23:30:32 INFO werkzeug: 192.168.1.23 - - [30/Sep/2025 23:30:32] "[35m[1mGET /transcode/status HTTP/1.1[0m" 503 -
2025-09-30 23:30:37 ERROR app.services.transcoder_client: Transcoder service request failed: HTTPConnectionPool(host='localhost', port=5003): Max retries exceeded with url: /transcode/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65e6d5eef0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-09-30 23:30:37 INFO werkzeug: 192.168.1.23 - - [30/Sep/2025 23:30:37] "[35m[1mGET /transcode/status HTTP/1.1[0m" 503 -
2025-09-30 23:30:42 ERROR app.services.transcoder_client: Transcoder service request failed: HTTPConnectionPool(host='localhost', port=5003): Max retries exceeded with url: /transcode/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65e6e051b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-09-30 23:30:42 INFO werkzeug: 192.168.1.23 - - [30/Sep/2025 23:30:42] "[35m[1mGET /transcode/status HTTP/1.1[0m" 503 -
2025-09-30 23:30:47 ERROR app.services.transcoder_client: Transcoder service request failed: HTTPConnectionPool(host='localhost', port=5003): Max retries exceeded with url: /transcode/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65e6e061a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-09-30 23:30:47 INFO werkzeug: 192.168.1.23 - - [30/Sep/2025 23:30:47] "[35m[1mGET /transcode/status HTTP/1.1[0m" 503 -
2025-09-30 23:30:52 ERROR app.services.transcoder_client: Transcoder service request failed: HTTPConnectionPool(host='localhost', port=5003): Max retries exceeded with url: /transcode/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65e6e04160>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-09-30 23:30:52 INFO werkzeug: 192.168.1.23 - - [30/Sep/2025 23:30:52] "[35m[1mGET /transcode/status HTTP/1.1[0m" 503 -
2025-09-30 23:30:58 ERROR app.services.transcoder_client: Transcoder service request failed: HTTPConnectionPool(host='localhost', port=5003): Max retries exceeded with url: /transcode/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65e6e07400>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-09-30 23:30:58 INFO werkzeug: 192.168.1.23 - - [30/Sep/2025 23:30:58] "[35m[1mGET /transcode/status HTTP/1.1[0m" 503 -
2025-09-30 23:31:03 ERROR app.services.transcoder_client: Transcoder service request failed: HTTPConnectionPool(host='localhost', port=5003): Max retries exceeded with url: /transcode/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65e6d5f190>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-09-30 23:31:03 INFO werkzeug: 192.168.1.23 - - [30/Sep/2025 23:31:03] "[35m[1mGET /transcode/status HTTP/1.1[0m" 503 -
2025-09-30 23:31:08 ERROR app.services.transcoder_client: Transcoder service request failed: HTTPConnectionPool(host='localhost', port=5003): Max retries exceeded with url: /transcode/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65e6e04250>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-09-30 23:31:08 INFO werkzeug: 192.168.1.23 - - [30/Sep/2025 23:31:08] "[35m[1mGET /transcode/status HTTP/1.1[0m" 503 -
2025-09-30 23:31:13 ERROR app.services.transcoder_client: Transcoder service request failed: HTTPConnectionPool(host='localhost', port=5003): Max retries exceeded with url: /transcode/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65e6e06b30>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-09-30 23:31:13 INFO werkzeug: 192.168.1.23 - - [30/Sep/2025 23:31:13] "[35m[1mGET /transcode/status HTTP/1.1[0m" 503 -
2025-09-30 23:31:17 ERROR app.services.transcoder_client: Transcoder service request failed: HTTPConnectionPool(host='localhost', port=5003): Max retries exceeded with url: /transcode/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65e6e05a50>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-09-30 23:31:17 INFO werkzeug: 192.168.1.23 - - [30/Sep/2025 23:31:17] "[35m[1mGET /transcode/status HTTP/1.1[0m" 503 -
2025-09-30 23:31:22 ERROR app.services.transcoder_client: Transcoder service request failed: HTTPConnectionPool(host='localhost', port=5003): Max retries exceeded with url: /transcode/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65e6d5d3f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-09-30 23:31:22 INFO werkzeug: 192.168.1.23 - - [30/Sep/2025 23:31:22] "[35m[1mGET /transcode/status HTTP/1.1[0m" 503 -
2025-09-30 23:31:27 ERROR app.services.transcoder_client: Transcoder service request failed: HTTPConnectionPool(host='localhost', port=5003): Max retries exceeded with url: /transcode/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65e6e04dc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-09-30 23:31:27 INFO werkzeug: 192.168.1.23 - - [30/Sep/2025 23:31:27] "[35m[1mGET /transcode/status HTTP/1.1[0m" 503 -
2025-09-30 23:31:32 ERROR app.services.transcoder_client: Transcoder service request failed: HTTPConnectionPool(host='localhost', port=5003): Max retries exceeded with url: /transcode/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65e6e05f30>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-09-30 23:31:32 INFO werkzeug: 192.168.1.23 - - [30/Sep/2025 23:31:32] "[35m[1mGET /transcode/status HTTP/1.1[0m" 503 -
2025-09-30 23:31:37 ERROR app.services.transcoder_client: Transcoder service request failed: HTTPConnectionPool(host='localhost', port=5003): Max retries exceeded with url: /transcode/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65e6e047f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-09-30 23:31:37 INFO werkzeug: 192.168.1.23 - - [30/Sep/2025 23:31:37] "[35m[1mGET /transcode/status HTTP/1.1[0m" 503 -
2025-09-30 23:31:42 ERROR app.services.transcoder_client: Transcoder service request failed: HTTPConnectionPool(host='localhost', port=5003): Max retries exceeded with url: /transcode/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65e6e06fe0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-09-30 23:31:42 INFO werkzeug: 192.168.1.23 - - [30/Sep/2025 23:31:42] "[35m[1mGET /transcode/status HTTP/1.1[0m" 503 -
2025-09-30 23:31:47 ERROR app.services.transcoder_client: Transcoder service request failed: HTTPConnectionPool(host='localhost', port=5003): Max retries exceeded with url: /transcode/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65e6e046a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-09-30 23:31:47 INFO werkzeug: 192.168.1.23 - - [30/Sep/2025 23:31:47] "[35m[1mGET /transcode/status HTTP/1.1[0m" 503 -
2025-09-30 23:31:52 ERROR app.services.transcoder_client: Transcoder service request failed: HTTPConnectionPool(host='localhost', port=5003): Max retries exceeded with url: /transcode/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65e6e06cb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-09-30 23:31:52 INFO werkzeug: 192.168.1.23 - - [30/Sep/2025 23:31:52] "[35m[1mGET /transcode/status HTTP/1.1[0m" 503 -
2025-09-30 23:31:57 ERROR app.services.transcoder_client: Transcoder service request failed: HTTPConnectionPool(host='localhost', port=5003): Max retries exceeded with url: /transcode/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65e6e05c00>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-09-30 23:31:57 INFO werkzeug: 192.168.1.23 - - [30/Sep/2025 23:31:57] "[35m[1mGET /transcode/status HTTP/1.1[0m" 503 -
2025-09-30 23:32:02 ERROR app.services.transcoder_client: Transcoder service request failed: HTTPConnectionPool(host='localhost', port=5003): Max retries exceeded with url: /transcode/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65e6e04bb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-09-30 23:32:02 INFO werkzeug: 192.168.1.23 - - [30/Sep/2025 23:32:02] "[35m[1mGET /transcode/status HTTP/1.1[0m" 503 -
2025-09-30 23:32:07 ERROR app.services.transcoder_client: Transcoder service request failed: HTTPConnectionPool(host='localhost', port=5003): Max retries exceeded with url: /transcode/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65e6d5f910>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-09-30 23:32:07 INFO werkzeug: 192.168.1.23 - - [30/Sep/2025 23:32:07] "[35m[1mGET /transcode/status HTTP/1.1[0m" 503 -
2025-09-30 23:32:12 ERROR app.services.transcoder_client: Transcoder service request failed: HTTPConnectionPool(host='localhost', port=5003): Max retries exceeded with url: /transcode/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65e5490820>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-09-30 23:32:12 INFO werkzeug: 192.168.1.23 - - [30/Sep/2025 23:32:12] "[35m[1mGET /transcode/status HTTP/1.1[0m" 503 -
2025-09-30 23:32:17 ERROR app.services.transcoder_client: Transcoder service request failed: HTTPConnectionPool(host='localhost', port=5003): Max retries exceeded with url: /transcode/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65e6e07640>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-09-30 23:32:17 INFO werkzeug: 192.168.1.23 - - [30/Sep/2025 23:32:17] "[35m[1mGET /transcode/status HTTP/1.1[0m" 503 -
2025-09-30 23:32:22 ERROR app.services.transcoder_client: Transcoder service request failed: HTTPConnectionPool(host='localhost', port=5003): Max retries exceeded with url: /transcode/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65e6e053c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-09-30 23:32:22 INFO werkzeug: 192.168.1.23 - - [30/Sep/2025 23:32:22] "[35m[1mGET /transcode/status HTTP/1.1[0m" 503 -
2025-09-30 23:32:27 ERROR app.services.transcoder_client: Transcoder service request failed: HTTPConnectionPool(host='localhost', port=5003): Max retries exceeded with url: /transcode/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65e6e06650>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-09-30 23:32:27 INFO werkzeug: 192.168.1.23 - - [30/Sep/2025 23:32:27] "[35m[1mGET /transcode/status HTTP/1.1[0m" 503 -
2025-09-30 23:32:32 ERROR app.services.transcoder_client: Transcoder service request failed: HTTPConnectionPool(host='localhost', port=5003): Max retries exceeded with url: /transcode/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65e6e07d30>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-09-30 23:32:32 INFO werkzeug: 192.168.1.23 - - [30/Sep/2025 23:32:32] "[35m[1mGET /transcode/status HTTP/1.1[0m" 503 -
2025-09-30 23:32:37 ERROR app.services.transcoder_client: Transcoder service request failed: HTTPConnectionPool(host='localhost', port=5003): Max retries exceeded with url: /transcode/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65e5490370>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-09-30 23:32:37 INFO werkzeug: 192.168.1.23 - - [30/Sep/2025 23:32:37] "[35m[1mGET /transcode/status HTTP/1.1[0m" 503 -
2025-09-30 23:32:42 ERROR app.services.transcoder_client: Transcoder service request failed: HTTPConnectionPool(host='localhost', port=5003): Max retries exceeded with url: /transcode/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65e6e04490>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-09-30 23:32:42 INFO werkzeug: 192.168.1.23 - - [30/Sep/2025 23:32:42] "[35m[1mGET /transcode/status HTTP/1.1[0m" 503 -
2025-09-30 23:32:47 ERROR app.services.transcoder_client: Transcoder service request failed: HTTPConnectionPool(host='localhost', port=5003): Max retries exceeded with url: /transcode/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65e6e06410>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-09-30 23:32:47 INFO werkzeug: 192.168.1.23 - - [30/Sep/2025 23:32:47] "[35m[1mGET /transcode/status HTTP/1.1[0m" 503 -
2025-09-30 23:32:52 ERROR app.services.transcoder_client: Transcoder service request failed: HTTPConnectionPool(host='localhost', port=5003): Max retries exceeded with url: /transcode/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65e6e04160>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-09-30 23:32:52 INFO werkzeug: 192.168.1.23 - - [30/Sep/2025 23:32:52] "[35m[1mGET /transcode/status HTTP/1.1[0m" 503 -
2025-09-30 23:32:57 ERROR app.services.transcoder_client: Transcoder service request failed: HTTPConnectionPool(host='localhost', port=5003): Max retries exceeded with url: /transcode/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65e6d5ebc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-09-30 23:32:57 INFO werkzeug: 192.168.1.23 - - [30/Sep/2025 23:32:57] "[35m[1mGET /transcode/status HTTP/1.1[0m" 503 -
2025-09-30 23:33:02 ERROR app.services.transcoder_client: Transcoder service request failed: HTTPConnectionPool(host='localhost', port=5003): Max retries exceeded with url: /transcode/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65e5490460>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-09-30 23:33:02 INFO werkzeug: 192.168.1.23 - - [30/Sep/2025 23:33:02] "[35m[1mGET /transcode/status HTTP/1.1[0m" 503 -
2025-09-30 23:33:07 ERROR app.services.transcoder_client: Transcoder service request failed: HTTPConnectionPool(host='localhost', port=5003): Max retries exceeded with url: /transcode/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65e6e05900>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-09-30 23:33:07 INFO werkzeug: 192.168.1.23 - - [30/Sep/2025 23:33:07] "[35m[1mGET /transcode/status HTTP/1.1[0m" 503 -
2025-09-30 23:33:12 ERROR app.services.transcoder_client: Transcoder service request failed: HTTPConnectionPool(host='localhost', port=5003): Max retries exceeded with url: /transcode/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65e6e04d60>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-09-30 23:33:12 INFO werkzeug: 192.168.1.23 - - [30/Sep/2025 23:33:12] "[35m[1mGET /transcode/status HTTP/1.1[0m" 503 -
2025-09-30 23:33:17 ERROR app.services.transcoder_client: Transcoder service request failed: HTTPConnectionPool(host='localhost', port=5003): Max retries exceeded with url: /transcode/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65e6e061d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-09-30 23:33:17 INFO werkzeug: 192.168.1.23 - - [30/Sep/2025 23:33:17] "[35m[1mGET /transcode/status HTTP/1.1[0m" 503 -
2025-09-30 23:33:22 ERROR app.services.transcoder_client: Transcoder service request failed: HTTPConnectionPool(host='localhost', port=5003): Max retries exceeded with url: /transcode/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65e6e06cb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-09-30 23:33:22 INFO werkzeug: 192.168.1.23 - - [30/Sep/2025 23:33:22] "[35m[1mGET /transcode/status HTTP/1.1[0m" 503 -
2025-09-30 23:33:27 ERROR app.services.transcoder_client: Transcoder service request failed: HTTPConnectionPool(host='localhost', port=5003): Max retries exceeded with url: /transcode/status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f65e6e05bd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-09-30 23:33:27 INFO werkzeug: 192.168.1.23 - - [30/Sep/2025 23:33:27] "[35m[1mGET /transcode/status HTTP/1.1[0m" 503 -
